### ISSUE TITLE
Le mode alarme (Présent) ( Alarm Home) ne marche pas

### ISSUE THREAD

**Issue by mrgoodfriend** [gvigroux/freebox_home#1]
Malgré le renvoi de la focntion alarm_home vers alarm night, l'activation ne se fait pas.

Après investigation Alarm_home n'est pas ajouté dans les supported features

Line 133
self._supported_features = SUPPORT_ALARM_ARM_AWAY | SUPPORT_ALARM_ARM_NIGHT 

à remplacer par 
 self._supported_features = SUPPORT_ALARM_ARM_AWAY | SUPPORT_ALARM_ARM_NIGHT | SUPPORT_ALARM_ARM_HOME

**Comment by gvigroux** [comment]
Je viens de faire la mise a jour. Merci!
