### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by zonazonarisk** [gvigroux/freebox_home#4]
bonjour

connection impossible à la delta.

Logger: custom_components.freebox_home-main.config_flow
Source: custom_components/freebox_home-main/config_flow.py:122
Integration: freebox_home-main
First occurred: 13:37:41 (4 occurrences)
Last logged: 13:39:27

Request failed (APIResponse: {"uid": "53e2533c655c45b9e3ba5165c343c07a", "success": false, "missing_right": "home", "msg": "Cette application n'est pas autoris\u00e9e \u00e0 acc\u00e9der \u00e0 cette fonction", "result": {"password_salt": "h+fGwwhAlu3zqhxwikxmZFsMeT7k3T2+"}, "error_code": "insufficient_rights"})

**Comment by gvigroux** [comment]
En fait il faut faire ca pour donner les droits à HA d'acceder à la partie Freebox Home:
As explained during the setup, you have to go to: http://mafreebox.freebox.fr/#Fbx.os.app.settings.Accounts, open the "application" tab and add all access to the Home assistant application
