### ISSUE TITLE
Comment installer dans HA sur VM freebox delta

### ISSUE THREAD

**Issue by dbzzzde** [gvigroux/freebox_home#6]
Bonjour,

Je n'arrive pas a intégrer ce module dans Home Assistant qui est installer sur une VM de la Freebox delta.

Pouvez-vous m'aider ?

Cordialement.

**Comment by dbzzzde** [comment]
C'est bon, j'ai réussi a intégrer ce module dans Home assistant.

**Comment by gvigroux** [comment]
parfait :)
