### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by mwahamwa** [gvigroux/freebox_home#7]
DEVICE_CLASS_BATTERY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

DEVICE_CLASS_MOTION was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.MOTION instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

SUPPORT_ALARM_ARM_AWAY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

SUPPORT_STREAM was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.STREAM instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

DEVICE_CLASS_SHUTTER was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverDeviceClass.SHUTTER instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

RESULT_TYPE_ABORT was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use FlowResultType.ABORT instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues

**Comment by gvigroux** [comment]
Done :)
